services:
  - type: web
    name: tablitsya3
    env: docker
    region: frankfurt
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: DATABASE_URL
        fromDatabase:
          name: tablitsya3-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: tablitsya3-db
    databaseName: tablitsya3
    user: tablitsya3user
    region: frankfurt
    plan: free
    ipAllowList: []
