// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tablitsya3.Data;

#nullable disable

namespace Tablitsya3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
   protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
   .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

       NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tablitsya3.Data.Entities.CustomCompletionDateEntity", b =>
                {
     b.Property<int>("Id")
          .ValueGeneratedOnAdd()
            .HasColumnType("integer")
     .HasColumnName("id");

              NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

   b.Property<DateTime>("CompletionDate")
      .HasColumnType("timestamp with time zone")
    .HasColumnName("completion_date");

         b.Property<string>("OrderKey")
       .IsRequired()
             .HasMaxLength(200)
     .HasColumnType("character varying(200)")
    .HasColumnName("order_key");

                 b.Property<int?>("WorkshopDataEntityId")
      .HasColumnType("integer");

         b.HasKey("Id");

       b.HasIndex("OrderKey")
            .IsUnique();

          b.HasIndex("WorkshopDataEntityId");

      b.ToTable("custom_completion_dates");
 });

        modelBuilder.Entity("Tablitsya3.Data.Entities.OrderEntity", b =>
        {
       b.Property<int>("Id")
    .ValueGeneratedOnAdd()
       .HasColumnType("integer")
            .HasColumnName("id");

         NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

          b.Property<DateTime>("OrderDate")
     .HasColumnType("timestamp with time zone")
                .HasColumnName("order_date");

        b.Property<string>("OrderName")
               .IsRequired()
       .HasMaxLength(500)
    .HasColumnType("character varying(500)")
     .HasColumnName("order_name");

  b.Property<double>("SquareMeters")
       .HasColumnType("double precision")
         .HasColumnName("square_meters");

          b.Property<int?>("WorkshopDataEntityId")
  .HasColumnType("integer");

   b.Property<int>("WorkshopNumber")
     .HasColumnType("integer")
             .HasColumnName("workshop_number");

          b.HasKey("Id");

       b.HasIndex("WorkshopDataEntityId");

       b.HasIndex("WorkshopNumber", "OrderDate");

b.ToTable("orders");
         });

      modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopCapacityEntity", b =>
       {
     b.Property<int>("Id")
.ValueGeneratedOnAdd()
      .HasColumnType("integer")
           .HasColumnName("id");

      NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

          b.Property<int>("Capacity")
         .HasColumnType("integer")
      .HasColumnName("capacity");

        b.Property<int?>("WorkshopDataEntityId")
    .HasColumnType("integer");

             b.Property<int>("WorkshopNumber")
  .HasColumnType("integer")
       .HasColumnName("workshop_number");

b.HasKey("Id");

         b.HasIndex("WorkshopDataEntityId");

       b.HasIndex("WorkshopNumber")
               .IsUnique();

     b.ToTable("workshop_capacities");
        });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopDataEntity", b =>
      {
 b.Property<int>("Id")
        .ValueGeneratedOnAdd()
    .HasColumnType("integer")
   .HasColumnName("id");

    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

        b.Property<int>("DaysBeforeProduction")
     .HasColumnType("integer")
            .HasColumnName("days_before_production");

        b.Property<DateTime>("LastUpdated")
         .HasColumnType("timestamp with time zone")
         .HasColumnName("last_updated");

            b.Property<int>("ProductionLeadTime")
            .HasColumnType("integer")
      .HasColumnName("production_lead_time");

         b.Property<DateTime>("StartDate")
     .HasColumnType("timestamp with time zone")
        .HasColumnName("start_date");

      b.HasKey("Id");

        b.ToTable("workshop_data");
        });

   modelBuilder.Entity("Tablitsya3.Data.Entities.CustomCompletionDateEntity", b =>
 {
              b.HasOne("Tablitsya3.Data.Entities.WorkshopDataEntity", null)
         .WithMany("CustomCompletionDates")
          .HasForeignKey("WorkshopDataEntityId")
         .OnDelete(DeleteBehavior.Cascade);
   });

    modelBuilder.Entity("Tablitsya3.Data.Entities.OrderEntity", b =>
       {
      b.HasOne("Tablitsya3.Data.Entities.WorkshopDataEntity", null)
     .WithMany("Orders")
         .HasForeignKey("WorkshopDataEntityId")
         .OnDelete(DeleteBehavior.Cascade);
 });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopCapacityEntity", b =>
 {
          b.HasOne("Tablitsya3.Data.Entities.WorkshopDataEntity", null)
  .WithMany("WorkshopCapacities")
     .HasForeignKey("WorkshopDataEntityId")
        .OnDelete(DeleteBehavior.Cascade);
       });

     modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopDataEntity", b =>
                {
          b.Navigation("CustomCompletionDates");

         b.Navigation("Orders");

   b.Navigation("WorkshopCapacities");
           });
#pragma warning restore 612, 618
   }
  }
}
