// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tablitsya3.Data;

#nullable disable

namespace Tablitsya3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tablitsya3.Data.Entities.CustomCompletionDateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("completion_date");

                    b.Property<string>("OrderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("order_key");

                    b.HasKey("Id");

                    b.HasIndex("OrderKey")
                        .IsUnique();

                    b.ToTable("custom_completion_dates", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.DefectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DefectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("defect_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRepairable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_repairable");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<int>("ProductionStage")
                        .HasColumnType("integer")
                        .HasColumnName("production_stage");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qr_code");

                    b.Property<string>("RepairNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repair_notes");

                    b.Property<int?>("RepairedByWorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("repaired_by_worker_id");

                    b.Property<DateTime?>("RepairedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("repaired_date");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.Property<int?>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("PartId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerId");

                    b.ToTable("defects", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.ImportedProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("imported_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("material_cost");

                    b.Property<decimal>("OperationCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("operation_cost");

                    b.Property<int>("PartsCount")
                        .HasColumnType("integer")
                        .HasColumnName("parts_count");

                    b.Property<int>("ProductsCount")
                        .HasColumnType("integer")
                        .HasColumnName("products_count");

                    b.Property<string>("ProjectUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_uuid");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<double>("TotalSquareMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("total_square_meters");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.HasIndex("ProjectUuid")
                        .IsUnique();

                    b.ToTable("imported_projects", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("order_name");

                    b.Property<double>("SquareMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("square_meters");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopNumber", "OrderDate");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.OriginalWorkshopEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("order_key");

                    b.Property<int>("OriginalWorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("original_workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("OrderKey")
                        .IsUnique();

                    b.ToTable("original_workshops", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.PartEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("CutCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cut_completed_date");

                    b.Property<DateTime?>("DrillingCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("drilling_completed_date");

                    b.Property<DateTime?>("EdgeBandingCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edge_banding_completed_date");

                    b.Property<string>("EdgeBandingCompletedDates")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("edge_banding_completed_dates");

                    b.Property<int>("EdgeBandingSidesCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("edge_banding_sides_completed");

                    b.Property<int>("EdgeBandingSidesRequired")
                        .HasColumnType("integer")
                        .HasColumnName("edge_banding_sides_required");

                    b.Property<bool>("IsCutCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cut_completed");

                    b.Property<bool>("IsDrillingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_drilling_completed");

                    b.Property<bool>("IsEdgeBandingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edge_banding_completed");

                    b.Property<bool>("IsPackingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_packing_completed");

                    b.Property<bool>("IsSortingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sorting_completed");

                    b.Property<double>("Length")
                        .HasColumnType("double precision")
                        .HasColumnName("length");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("order_name");

                    b.Property<DateTime?>("PackingCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("packing_completed_date");

                    b.Property<int>("PartCounter")
                        .HasColumnType("integer")
                        .HasColumnName("part_counter");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<string>("ProjectExternalUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_external_uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresCutting")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_cutting");

                    b.Property<bool>("RequiresDrilling")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_drilling");

                    b.Property<bool>("RequiresEdgeBanding")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_edge_banding");

                    b.Property<bool>("RequiresPacking")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_packing");

                    b.Property<bool>("RequiresSorting")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_sorting");

                    b.Property<DateTime?>("SortingCompletedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sorting_completed_date");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_file_name");

                    b.Property<double>("Thickness")
                        .HasColumnType("double precision")
                        .HasColumnName("thickness");

                    b.Property<double>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("OrderName");

                    b.HasIndex("SourceFileName");

                    b.HasIndex("ProjectExternalUuid", "PartId", "PartCounter")
                        .IsUnique();

                    b.HasIndex("IsCutCompleted", "IsEdgeBandingCompleted", "IsDrillingCompleted", "IsSortingCompleted", "IsPackingCompleted");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("material_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("OperationCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("operation_cost");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProjectUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectUuid", "ProductId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.ScanLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<int>("PartId")
                        .HasColumnType("integer")
                        .HasColumnName("part_id");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("qr_code");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scan_date");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.Property<int?>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("QRCode");

                    b.HasIndex("ScanDate");

                    b.HasIndex("WorkerId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("scan_logs", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedStages")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("allowed_stages");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pin_code");

                    b.Property<string>("PinCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pin_code_hash");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("WorkerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("worker_code");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("WorkerCode")
                        .IsUnique();

                    b.HasIndex("WorkshopNumber");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkerKpiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgTimePerPart")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_time_per_part");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<int>("DefectsCount")
                        .HasColumnType("integer")
                        .HasColumnName("defects_count");

                    b.Property<int>("PartsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("parts_processed");

                    b.Property<int>("ProductionStage")
                        .HasColumnType("integer")
                        .HasColumnName("production_stage");

                    b.Property<double>("TotalSquareMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("total_square_meters");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<int>("WorkMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("work_minutes");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkerId", "Date", "ProductionStage")
                        .IsUnique();

                    b.ToTable("worker_kpis", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkerSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastScanTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_scan_time");

                    b.Property<int>("ScansCount")
                        .HasColumnType("integer")
                        .HasColumnName("scans_count");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_token");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("WorkerId");

                    b.HasIndex("WorkstationId");

                    b.HasIndex("IsActive", "WorkstationId");

                    b.ToTable("worker_sessions", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopCapacityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopNumber");

                    b.ToTable("workshop_capacities", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysBeforeProduction")
                        .HasColumnType("integer")
                        .HasColumnName("days_before_production");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("ProductionLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("production_lead_time");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("workshop_data", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopDaysBeforeProductionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysBeforeProduction")
                        .HasColumnType("integer")
                        .HasColumnName("days_before_production");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopNumber");

                    b.ToTable("workshop_days_before_production", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkshopProductionLeadTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductionLeadTime")
                        .HasColumnType("integer")
                        .HasColumnName("production_lead_time");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopNumber");

                    b.ToTable("workshop_production_lead_times", (string)null);
                });

            modelBuilder.Entity("Tablitsya3.Data.Entities.WorkstationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DeviceIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("ProductionStage")
                        .HasColumnType("integer")
                        .HasColumnName("production_stage");

                    b.Property<bool>("RequiresWorkerAuth")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_worker_auth");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_timeout_minutes");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("station_code");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<int>("WorkshopNumber")
                        .HasColumnType("integer")
                        .HasColumnName("workshop_number");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductionStage");

                    b.HasIndex("StationCode")
                        .IsUnique();

                    b.HasIndex("WorkshopNumber");

                    b.ToTable("workstations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
